all: g++ cl

g++:
	g++ -std=c++11 truck_tester.cpp truck.cpp package.cpp package_exception.cpp letter.cpp box.cpp crate.cpp crate_metal.cpp crate_wood.cpp
cl:
	cl -std=c++11 truck_tester.cpp truck.cpp package.cpp package_exception.cpp letter.cpp box.cpp crate.cpp crate_metal.cpp crate_wood.cpp
		